### add company
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "MMM"
}

### get companies
GET http://localhost:8080/company?page=0&size=5
Content-Type: application/json

### get finance spec. company
GET http://localhost:8080/finance/dividend/3M Company
Content-Type: application/json