### add company
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "NKE"
}

### get companies
GET http://localhost:8080/company?page=0&size=5
Content-Type: application/json

### get finance spec. company
GET http://localhost:8080/finance/dividend/NIKE, Inc.
Content-Type: application/json

### autocomplete
GET http://localhost:8080/company/autocomplete?keyword=A